<?php

return [
    'CLINIC_OPEN_TIME' => '09:00:00',
    'CLINIC_CLOSE_TIME' => '18:00:00',
    'DEFAULT_APPOINTMENT_TIME_SPAN' => 30, // 30 min
    'GAP_BETWEEN_APPOINTMENTS' => 0,
    'MAIL_DRIVER' => 'smtp',
    'MAIL_HOST' => 'mymails.chetu.com',
    'MAIL_PORT' => 25,
    'MAIL_FROM_NAME' => 'azmensclinic1',
    'MAIL_FROM_ADDRESS' => 'sureshc@chetu.com',
    'MAIL_ENCRYPTION' => 'tls',
    'PATIENT_ROLE_SLUG' => 'patient',
    'PATIENT_ROLE_ID' => 6,
    'DOCTOR_ROLE_SLUG' => 'doctor',
    'DOCTOR_ROLE_ID' => 5,
    'ADMIN_ROLE_SLUG' => 'admin',
    'AUTHORS_ROLE_SLUG' => 'authors',
    'USER_ROLE_SLUG' => 'user',
    'APPOINTMENT_SET_FLAG' => 0,
    'APPOINTMENT_NO_SET_FLAG' => 1,
    'APPOINTMENT_AFTER_REPORT_FLAG' => 4,
    'BRONZE_PKG_ID' => 1,
    'SILVER_PKG_ID' => 2,
    'GOLD_PKG_ID' => 3,
    'SAVED_DATA' => 'Data Saved Successfully',
    'UPDATED_DATA' => 'Data Updated Successfully',
    'ERROR_OCCURED' => 'Error occured. Please try after some time.',
    'PAGE_NOT_FOUND' => 'Page Not Found',
    'DELETED_DATA' => 'Data Deleted Successfully',
    'EMAIL_ALREADY_EXIST' => 'Email id you provided is already registered.',
    'APPOINTMENT_END' => 'Appointment Ended Successfully.',
    'APPOINTMENT_HOLD' => 'Appointment put on the hold successfully.',
    'ROLE_NOT_FETCH' => 'Cannot fetch role from database.',
    'FOLLOWUP_UPDATED' => 'Follow Up of this appointment has been updated successfully.',
    'IMAGE_VALIDATION' => 'Please upload a valid image (jpeg,png,pdf).',
    'ROLE_CREATION' => 'Role Created successfully.',
    'PATIENT_SELECT' => 'Please select patient from Select Patient dropdown.',
    'CATEGORY_NOT_FOUND' => 'Category not found.',
    'ADD_CART' => 'Package added to cart successfully.',
    'EMPTY_PACKAGE' => 'This package is empty.',
    'EXCEL_ERROR' => 'Category save failed. Please try again witha valid excel file.',
    'EXCEL_VALID' => 'Please upload a valid excel file.',
    'IMPORTED_DATA' => 'Data imported successfully',
    'INVENTORY_VALID' => 'Inventory Imports Failed. Please try again witha valid excel file.',
    'NETWORK_ERROR' => '* Some network issue generated errors',
    'SKU_VALUE' => 'Product with given sku value not found',
    'EMI_PLAN' => 'Please select prefered EMI option or make complete payment again.',
    'SESSION_EXPIRED' => 'Your session expired. Please try again',
    'DUE_DATE' => 'Selected due date out of limit.',
    'PRINT_FORM'=> 'Your order placed successfully, Please print the listed forms.',
    'PARTIAL_PAYMENT' => 'Your payment received successfully, Please do the complete payment for this order.',
    'ORDER_ERROR' => "Your orders didn't find in the application.",
    'URL_EXPIRED' => 'The url seeme to be expired or invalid.',
    'AUTH_VALID' => 'Please set the valid authntication detail'

];
